 Energy balance per zone
 
  Zonenr Rel_BAL  BAL_ENERGY= -DQAIRdt  +QHEAT     -QCOOL    +QINF      +QVENT       +QCOUPL    -QTRANS  +QGAININT  +QWGAIN    +QSOLGAIN  +QSOLAIR
   -     %        kJ          kJ         kJ          kJ         kJ         kJ         kJ          kJ         kJ         kJ         kJ         kJ
   1       0.00   1.044E-01 -5.070E+04  3.555E+08  0.000E+00 -2.979E+08 -8.136E+07  0.000E+00 -3.095E+08  2.187E+08  0.000E+00  1.032E+08  1.137E+07
 Energy balance for sum of all zone
   0       0.00   1.044E-01 -5.070E+04  3.555E+08  0.000E+00 -2.979E+08 -8.136E+07  0.000E+00 -3.095E+08  2.187E+08  0.000E+00  1.032E+08  1.137E+07
